- name: Deploy Web Application
  hosts: webservers
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      tags: update

    - name: Install Nginx
      apt:
        name: nginx
        state: latest
      tags: nginx

    - name: Download index.html from GitHub
      get_url:
        url: "https://raw.githubusercontent.com/Champloot/automated-ci-cd-pipeline/main/ansible/files/index.html"
        dest: /var/www/html/index.html
        mode: '0644'
        force: yes
      become: yes

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: yes
      tags: service

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
        
